### ISSUE TITLE
关于第二阶段训练多进程处理数据，can't pickle Environment objects

### ISSUE THREAD

**Issue by hofirstb19** [awei669/VQ-Font#11]
当在cfg中设置n_workers大于0时，终端就会报错，提示：
File "train.py", line 211, in train
    trainer.train(trn_loader, st_step, cfg["iter"], component_objects, chars_sim_dict)
  File "F:\tools\VQ-Font-main\trainer\combined_trainer.py", line 40, in train
    content_imgs, trg_unis, style_sample_index, trg_sample_index, ref_unis) in cyclize(loader):
  File "F:\tools\VQ-Font-main\datasets\datautils.py", line 12, in cyclize
    for x in loader:
  File "D:\anaconda3\envs\vq\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
  File "D:\anaconda3\envs\vq\lib\site-packages\torch\utils\data\dataloader.py", line 1048, in __init__
    self._popen = self._Popen(self)
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\envs\vq\lib\multiprocessing\context.py", line 322, in _Popen
TypeError: can't pickle Environment objects

当想避免使用多进程处理数据，将n_works设置为0。此时又出现了一个新的Error：
Traceback (most recent call last):
  File "F:/tools/VQ-Font-main/train.py", line 222, in <module>
    main()
  File "F:/tools/VQ-Font-main/train.py", line 218, in main
    train(args, cfg)
  File "F:/tools/VQ-Font-main/train.py", line 127, in train
    data_meta = load_json(cfg.data_meta)  # load train.json
KeyboardInterrupt

想请教一下，多进程处理数据时，应该如何辨别Environment对象？此对象是否为代码中出现的 env ？关于避免多线程处理数据后，出现的新Error应该怎么应对呢？

代码运行环境 Windows 11; python 3.7

**Comment by aceliuchanghong** [comment]
n_workers大于0时，终端就会报错,这个一般是windows的问题,一般再linux下面不会报错
