### ISSUE TITLE
How to change kshot？

### ISSUE THREAD

**Issue by fly-fei-li** [awei669/VQ-Font#3]
Is it necessary to adjust other parameters while adjusting the kshot? When I try to adjust the number of kshot, I encounter the following error：

Traceback (most recent call last):
  File "train.py", line 220, in <module>
    main()
  File "train.py", line 216, in main
    train(args, cfg)
  File "train.py", line 209, in train
    trainer.train(trn_loader, st_step, cfg["iter"], component_objects, chars_sim_dict)
  File "/disk3/lyf/VQ-Font/trainer/combined_trainer.py", line 161, in train
    bs_component_embeddings, chars_sim_dict)
  File "/disk3/lyf/VQ-Font/evaluator.py", line 50, in cp_validation
    phase=phase, reduction=reduction)
  File "/home/mac418/miniconda3/envs/VQ_Font/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/disk3/lyf/VQ-Font/evaluator.py", line 18, in decorated
    ret = val_fn(self, gen, *args, **kwargs)
  File "/disk3/lyf/VQ-Font/evaluator.py", line 57, in comparable_val_saveimg
    reduction=reduction)
  File "/home/mac418/miniconda3/envs/VQ_Font/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/disk3/lyf/VQ-Font/evaluator.py", line 18, in decorated
    ret = val_fn(self, gen, *args, **kwargs)
  File "/disk3/lyf/VQ-Font/evaluator.py", line 75, in infer_loader
    reduction=reduction)
  File "/disk3/lyf/VQ-Font/model/generator.py", line 192, in infer
    style_components = self.Get_style_components(learned_components, reference_feats)  # [B,N,C]
  File "/home/mac418/miniconda3/envs/VQ_Font/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk3/lyf/VQ-Font/model/Component_Attention_Module.py", line 73, in forward
    value_reference_matrix)
  File "/disk3/lyf/VQ-Font/model/Component_Attention_Module.py", line 54, in cross_attention
    scores = torch.matmul(key, query)  # [b m khw n]
RuntimeError: The size of tensor a (24) must match the size of tensor b (16) at non-singleton dimension 0

**Comment by awei669** [comment]
Hello, the current repo is suitable for the scenario of kshot=3. If you want to modify this value during training, you may need to modify some code accordingly. In addition, the reason seems like I do not use the kshot hyperparameter globally.

You can try to modify the code, I will fix this problem later, thank you for pointing this.

**Comment by fly-fei-li** [comment]
Thank you!
